name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.11.0
              uses: actions/setup-node@v2
              with:
                  node-version: 14.11.0

            - name: Yarn & Build
              run: |
                  yarn install --frozen-lockfile
                  yarn rw build
              env:
                  CI: true

            - name: Run Yarn Test with Coverage
              run: yarn test:coverage
              env:
                  CI: true

            - name: Upload Coverage to codecov
              if: github.ref == 'refs/heads/master'
              uses: codecov/codecov-action@v1.0.3
              with:
                  token: ${{secrets.CODECOV_TOKEN}}
                  file: ./coverage/clover.xml
